#ifndef AUDIO_SETTINGS
#define AUDIO_SETTINGS

#define SAMPLING_FREQ 		(44100)
#define SAMPLING_FRAME      (16)
#define SAMPLING_FRAME_BYTE (SAMPLING_FRAME*sizeof(float))
#define BUFFER_COUNT		(3)
#define SAMPLING_CHANNELS   (2)
#define SAMPLING_BUFFER		(SAMPLING_CHANNELS * SAMPLING_FRAME)
#define CODEC_PHASE         (-1)

#endif